ALTER TABLE "Podcast"
  ADD COLUMN "language" TEXT NOT NULL DEFAULT 'en',
  ADD COLUMN "format" TEXT NOT NULL DEFAULT 'conversation',
  ADD COLUMN "length" TEXT NOT NULL DEFAULT 'medium',
  ADD COLUMN "tone" TEXT NOT NULL DEFAULT 'engaging',
  ADD COLUMN "voice1" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "voice2" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "engine" TEXT NOT NULL DEFAULT 'neural',
  ADD COLUMN "status" TEXT NOT NULL DEFAULT 'script_ready',
  ADD COLUMN "stage" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "error" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "audioKey" TEXT,
  ADD COLUMN "audioSize" INTEGER,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
